export const
    TASK_UNSTARTED = 'Unstarted',
    TASK_IN_PROGRESS = 'In Progress',
    TASK_COMPLETED = 'Completed',
    TASK_STATUSES = [TASK_UNSTARTED, TASK_IN_PROGRESS, TASK_COMPLETED],
    CREATE_TASK = 'CREATE_TASK',
    EDIT_STATUS = 'EDIT_STATUS',
    FETCH_TASKS_STARTED = 'FETCH_TASKS_STARTED',
    FETCH_TASKS_SUCCEEDED = 'FETCH_TASKS_SUCCEEDED',
    FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED',
    CREATE_TASK_STARTED = 'CREATE_TASK_STARTED',
    CREATE_TASK_FAILED = 'CREATE_TASK_FAILED',
    CREATE_TASK_SUCCEEDED = 'CREATE_TASK_SUCCEEDED',
    EDIT_STATUS_SUCCEEDED = 'EDIT_STATUS_SUCCEEDED'
;